### ISSUE TITLE
Setting global type settings is bad

### ISSUE THREAD

**Issue by justin8** [andschwa/puppet-ghost#26]
Currently the blog module sets defaults for Exec and File. These can be interpreted at any point in a catalogue compilation and results in unintended side effects. Any file that is generated without a specific user/group will now default to one of the blog instances user/group settings for example.

**Comment by andschwa** [comment]
As far as I interpret [the docs](https://docs.puppetlabs.com/puppet/latest/reference/lang_defaults.html#area-of-effect) these defaults only affect classes and resources inside the blog module.

This is a non-issue unless you can demonstrate files declared outside of this module inheriting its defaults, in which case this needs to be looked into further.

**Comment by justin8** [comment]
Sorry you're right. It appears that has been fixed in puppet 3.x. I encountered that issue on some production systems when a dev pushed changes to a puppet 2.7 system in another module and it propagated to all sections of the catalogue compiled after.

**Comment by andschwa** [comment]
Ahh. Puppet bugs, I hate them. Sorry you ran into that! By the way, feel free to fix anything in this module, I'm always accepting PRs but don't actually manage systems with Puppet myself any more.
