### ISSUE TITLE
0.3.0 appears broken

### ISSUE THREAD

**Issue by danielfaulknor** [andschwa/puppet-ghost#28]
I installed the module and used the example from the readme but I'm getting a nice error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter blogs on Class[Ghost] at /etc/puppet/environments/production/modules/ibd_prod/manifests/modules.pp:36 on node web01.jax.netbydesign.nz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by andschwa** [comment]
Please post how you're using it and your Puppet version.

@petems can you test the readme example?

**Comment by danielfaulknor** [comment]
I have this in the file for my node:

```
class { ghost:
  blogs => {
    'dan_blog' => {
      'url'  => 'http://dangeek.nz/',
    }
  }
```

And version:

```
root@web01:~# puppet --version
3.8.1
root@web01:~#
```

**Comment by petems** [comment]
@danielfaulknor where did you get that example from? The creation of blogs via the `blogs` parameter got deprecated: (See https://github.com/andschwa/puppet-ghost/issues/16)

I think that should be:

```puppet
class {'ghost':
  include_nodejs => true,
}
->
ghost::blog{ 'dan_blog':
   url => 'http://dangeek.nz/',
}
```

**Comment by danielfaulknor** [comment]
Excellent, puppet is running without errors now.

I got it from the puppetforge page for this module: https://forge.puppetlabs.com/andschwa/ghost

**Comment by petems** [comment]
Ah ok, good point, forgot we need to do a new forge release to update the docs on the Forge (#25) 

Closing

**Comment by danielfaulknor** [comment]
@petems sorry would you mind editing out the URL from your comment? I forgot to edit it out, I'd rather not have that name associated with my full name. Cheers

**Comment by petems** [comment]
No worries, done :+1:

**Comment by andschwa** [comment]
Thanks @petems!
