### ISSUE TITLE
Could not find declared class ghost_blog_profile::basic

### ISSUE THREAD

**Issue by habitullence** [andschwa/puppet-ghost#32]
Followed https://github.com/andschwa/puppet-ghost#ghost-blog-profile verbatim and this is the error message.

**Comment by andschwa** [comment]
Sounds like you didn't add their module. I see the class right [here](https://github.com/petems/petems-ghost_blog_profile/blob/master/manifests/init.pp).

**Comment by habitullence** [comment]
Yeah, might have jumped the gun on opening this. Just looking into that now :)

**Comment by habitullence** [comment]
Ah! Sorry, I see how this is set up... PEBKAC ;P

**Comment by habitullence** [comment]
Great response time @andschwa :+1:

**Comment by andschwa** [comment]
No problem :smile:
